export const MUTATION_SIGN_IN = 'MUTATION_SIGN_IN';
export const MUTATION_SIGN_IN_SUCCESS = 'MUTATION_SIGN_IN_SUCCESS';
export const MUTATION_SIGN_IN_FAILED = 'MUTATION_SIGN_IN_FAILED';

export const MUTATION_SIGN_UP = 'MUTATION_SIGN_UP';
export const MUTATION_SIGN_UP_SUCCESS = 'MUTATION_SIGN_UP_SUCCESS';
export const MUTATION_SIGN_UP_FAILED = 'MUTATION_SIGN_UP_FAILED';
